### PR TITLE
Support txn [fix issue #22]

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Review by lyrixx — COMMENTED** [review]
Look good to me. Could you update the README?

**Comment by andre-exads** [comment]
@lyrixx Is that enough? :grin:

**Comment by lyrixx** [comment]
Yes, thanks

**Comment by lyrixx** [comment]
Thank you @andre-exads.

**Comment by lyrixx** [comment]
merged as f693be25288e33dfb3330818bdb174c8d47f3784

**Pull request closed without merging**
