### PR TITLE
Use PUT HTTP verb to register a service

### PR DESCRIPTION
**Pull request by francois-roget**
To create a new service in Consul, the PUT verb should be used with the API /catalog/register
See https://www.consul.io/api-docs/catalog#register-entity

### CODE REVIEW

**Comment by lyrixx** [comment]
Thanks

**Comment by francois-roget** [comment]
You're welcome. Thanks for the library.

**Comment by francois-roget** [comment]
How can I get this code in the official package? Could you please release a new version?

**Comment by lyrixx** [comment]
Here we go: v3.1.1

**Comment by francois-roget** [comment]
Thanks a lot

**Pull request merged**
